"""Weekly £45 manual payments to Agata (cleaning + cash-spend via tag rules)."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta
from typing import cast

import polars as pl

from flathold.bank_delta import read_existing_table
from flathold.manual_ledger import read_manual_ledger_table, write_manual_ledger_table

# Must stay aligned with ``_AGATA_WEEKLY_MANUAL_PREDICATE`` in ``rules_home_finance``.
AGATA_WEEKLY_MANUAL_DESCRIPTION = "Payment to Agata - weekly cleaning (manual)"

AGATA_WEEKLY_DEBIT = 45.0
AGATA_WEEKLY_ID_PREFIX = "manual-agata-weekly-"
# Legacy ids from before the name was corrected; still stripped on sync.
_LEGACY_AGA_WEEKLY_ID_PREFIX = "manual-aga-weekly-"

_MANUAL_PREFIX = "manual-"


@dataclass(frozen=True, slots=True)
class SyncAgataWeeklyResult:
    success: bool
    message: str
    n_rows: int


def _first_monday_on_or_after(d: date) -> date:
    return d + timedelta(days=(7 - d.weekday()) % 7)


def _iter_weekly_mondays(start: date, end: date):
    m = _first_monday_on_or_after(start)
    while m <= end:
        yield m
        m += timedelta(days=7)


def _earliest_data_date() -> date:
    dates: list[date] = []
    bank = read_existing_table()
    if bank is not None and len(bank) > 0:
        d = (
            bank.select(pl.col("Transaction Date").str.to_date("%d/%m/%Y").alias("d"))
            .get_column("d")
            .min()
        )
        if d is not None:
            dates.append(cast(date, d))
    manual = read_manual_ledger_table()
    if manual is not None and len(manual) > 0:
        d = (
            manual.select(pl.col("Transaction Date").str.to_date("%d/%m/%Y").alias("d"))
            .get_column("d")
            .min()
        )
        if d is not None:
            dates.append(cast(date, d))
    if not dates:
        return date.today() - timedelta(days=365)
    return min(dates)


def _agata_weekly_id(monday: date) -> str:
    return f"{_MANUAL_PREFIX}agata-weekly-{monday:%Y%m%d}"


def _weekly_programmatic_row_mask() -> pl.Expr:
    """Rows generated by this module (current or legacy id prefix)."""
    return pl.col("id").str.starts_with(AGATA_WEEKLY_ID_PREFIX) | pl.col("id").str.starts_with(
        _LEGACY_AGA_WEEKLY_ID_PREFIX
    )


def _next_transaction_counter(
    base: pl.DataFrame | None,
    pending: list[dict[str, object]],
    transaction_date_dd_mm_yyyy: str,
) -> int:
    nums: list[int] = []
    if base is not None and len(base) > 0:
        hit = base.filter(pl.col("Transaction Date") == transaction_date_dd_mm_yyyy)
        if len(hit) > 0:
            nums.extend(int(x) for x in hit.get_column("Transaction Counter").to_list())
    nums.extend(
        int(cast(int | float, r["Transaction Counter"]))
        for r in pending
        if str(r["Transaction Date"]) == transaction_date_dd_mm_yyyy
    )
    return max(nums, default=0) + 1


def sync_agata_weekly_manual_entries(
    *,
    until: date | None = None,
    start: date | None = None,
) -> SyncAgataWeeklyResult:
    """
    Replace all ``manual-agata-weekly-*`` (and legacy ``manual-aga-weekly-*``) rows with one £45
    debit per Monday from ``start`` through ``until`` (defaults: earliest date in bank/manual data,
    or last year if empty; ``until`` is today). Other manual rows are kept.
    """
    until_d = until if until is not None else date.today()
    start_d = start if start is not None else _earliest_data_date()
    if start_d > until_d:
        return SyncAgataWeeklyResult(
            success=False,
            message="start date is after until date.",
            n_rows=0,
        )

    existing = read_manual_ledger_table()
    base: pl.DataFrame | None = None
    if existing is not None and len(existing) > 0:
        b = existing.filter(~_weekly_programmatic_row_mask())
        base = b if len(b) > 0 else None

    pending: list[dict[str, object]] = []
    for monday in _iter_weekly_mondays(start_d, until_d):
        ds = monday.strftime("%d/%m/%Y")
        counter = _next_transaction_counter(base, pending, ds)
        pending.append(
            {
                "Transaction Counter": counter,
                "Transaction Date": ds,
                "Transaction Type": "MANUAL",
                "Sort Code": "",
                "Account Number": "",
                "Transaction Description": AGATA_WEEKLY_MANUAL_DESCRIPTION,
                "Debit Amount": AGATA_WEEKLY_DEBIT,
                "Credit Amount": 0.0,
                "id": _agata_weekly_id(monday),
                "year": monday.year,
                "month": monday.month,
                "day": monday.day,
            }
        )

    if not pending:
        try:
            write_manual_ledger_table(base if base is not None else pl.DataFrame())
        except ValueError as e:
            return SyncAgataWeeklyResult(success=False, message=str(e), n_rows=0)
        return SyncAgataWeeklyResult(
            success=True,
            message="No Monday in date range; removed Agata weekly rows if any.",
            n_rows=0,
        )

    agata_df = pl.DataFrame(pending)
    combined = pl.concat([base, agata_df], how="vertical") if base is not None else agata_df
    try:
        write_manual_ledger_table(combined)
    except ValueError as e:
        return SyncAgataWeeklyResult(success=False, message=str(e), n_rows=0)
    return SyncAgataWeeklyResult(
        success=True,
        message=(
            f"Wrote {len(pending)} weekly Agata row(s) from {start_d.isoformat()} through "
            f"{until_d.isoformat()} (Mondays)."
        ),
        n_rows=len(pending),
    )
