"""Seed rows for the ``tag_definitions`` Delta table (default when the table is created)."""

# (tag, counter_party, groups as tuple of TagGroup value strings).
# Kept in sync with rule tags; used only to initialize or merge into ``db/tag_definitions``.
TAG_DEFINITIONS_SEED_ROWS: tuple[tuple[str, bool, tuple[str, ...]], ...] = (
    ("dog-food", False, ()),
    ("us", False, ()),
    ("pets", False, ()),
    ("groomer", False, ()),
    ("insurance", False, ()),
    ("david-life-insurance", False, ()),
    ("health-insurance", False, ()),
    ("vitality", True, ("counter-party",)),
    ("house-insurance", False, ()),
    ("printer", False, ()),
    ("gas-and-electricity", False, ()),
    ("hyperoptic", True, ("counter-party",)),
    ("utilities", False, ("sector-codes",)),
    ("ring", True, ("counter-party",)),
    ("edinburgh-council", True, ("counter-party",)),
    ("council-tax", False, ()),
    ("tax", False, ()),
    ("factors", False, ()),
    ("mortgage", False, ()),
    ("loans", False, ("sector-codes",)),
    ("car", False, ()),
    ("cleaning", False, ("sector-codes",)),
    ("fresh-car", True, ("counter-party",)),
    ("kitchen", False, ()),
    ("disney", True, ("counter-party",)),
    ("netflix", True, ("counter-party",)),
    ("octopus", True, ("counter-party",)),
    ("youtube-premium", False, ()),
    ("entertainment", False, ("sector-codes",)),
    ("bbc", True, ("counter-party",)),
    ("tv-license", False, ()),
    ("eating-out", False, ()),
    ("williams-and-johnson", True, ("counter-party",)),
    ("dish-washer-tablets", False, ()),
    ("groceries", False, ("sector-codes",)),
    ("farmers-market", True, ("counter-party",)),
    ("abbis-pantry", True, ("counter-party",)),
    ("agata", True, ("counter-party",)),
    ("waitrose", True, ("counter-party",)),
    ("great-grog", True, ("counter-party",)),
    ("google", True, ("counter-party",)),
    ("field-doctor", True, ("counter-party",)),
    ("tescos", True, ("counter-party",)),
    ("dave", True, ("counter-party",)),
    ("claire", True, ("counter-party",)),
    ("chocolaterium", True, ("counter-party",)),
    ("aviva", True, ("counter-party",)),
    ("amazon", True, ("counter-party",)),
    ("amazon-spend", False, ()),
    ("borlands", True, ("counter-party",)),
    ("pet-plan", True, ("counter-party",)),
    ("hp", True, ("counter-party",)),
    ("ross-and-liddell", True, ("counter-party",)),
    ("smol", True, ("counter-party",)),
    ("natwest", True, ("counter-party",)),
    ("bos", True, ("counter-party",)),
    ("toyota-finance", True, ("counter-party",)),
    ("wren", True, ("counter-party",)),
    ("years", True, ("counter-party",)),
    ("cash", True, ("counter-party",)),
    ("cash-spend", False, ()),
    ("cash-withdrawal", False, ()),
    ("unknown-cash", False, ()),
    ("untagged-spend", False, ()),
    ("uncategorised-sector", False, ("sector-codes",)),
)

# Tags with ``calculated=True`` in seed (not applied by ``TAG_RULES``).
CALCULATED_TAG_NAMES: frozenset[str] = frozenset(
    {"unknown-cash", "untagged-spend", "uncategorised-sector"}
)
